### ISSUE TITLE
CHARM vectors for 4-color images?

### ISSUE THREAD

**Issue by EarlGlynn** [wnd-charm/wnd-charm#114]
For use with machine learning, I'd like to create CHARM vectors (.sig files) for TIFF images with 4 color planes:  red, green, blue and near-infrared.

Some questions:

1.  Are the signature files from wndchrm valid for a tiff with 4 color planes?  [See below.  The regular and long .sig files seem to be created now but have many 0s and some NaNs.]

2.  What changes in the code would permit creating color long (-cl) .sig files?  [See below for error message now.]

3.  What if I split the 4-color tiff into a 3 color (RGB) image and separate near-infrared image, and created a -c-l.sig for the color image and a -l.sig for the near infrared image?  Would combining the two sets of features make sense for machine learning?  What might be missing that way?

4.  Do you have any suggestions for processing a 4-color TIFF using the existing wndchrm software?

Thanks for any help or advice.

Some additional info:

Here's the tiffinfo from one of the files:

**tiffinfo train_0.tif**
```
TIFF Directory at offset 0x8 (8)
  Subfile Type: (0 = 0x0)
  Image Width: 256 Image Length: 256
  Bits/Sample: 16
  Sample Format: unsigned integer
  Compression Scheme: None
  Photometric Interpretation: RGB color
  Extra Samples: 1<assoc-alpha>
  Samples/Pixel: 4
  Rows/Strip: 256
  Planar Configuration: single image plane
  ImageDescription: {"shape": [256, 256, 4]}
  Software: tifffile.py
  DateTime: 2017:04:26 23:11:27

```
I can create a "regular" .sig file using version wndchrm 1.60-977f5f6 on a CentOS7 VM:

**wndchrm train  -m  train-tif-v2/train_0.tif  train.fit**
```
Adding 'train-tif-v2/train_0.sig' for sig calc.
processing 'train-tif-v2/train_0.sig' (index 0).
----------
Summary of 'train-tif-v2/train_0.tif' (1 samples total, 1 samples per image):
Single class '' with 0 samples. Suitable as a test/classification set only.
1 unknown samples.
----------
Saved dataset to 'train.fit'.

```
I can create a "long" .sig file:

**wndchrm train  -ml  train-tif-v2/train_0.tif  train.fit**
```
Adding 'train-tif-v2/train_0-l.sig' for sig calc.
processing 'train-tif-v2/train_0-l.sig' (index 0).
----------
Summary of 'train-tif-v2/train_0.tif' (1 samples total, 1 samples per image):
Single class '' with 0 samples. Suitable as a test/classification set only.
1 unknown samples.
----------
Saved dataset to 'train.fit'.

```
But there is a failure in creating a "long, color" .sig file:

**wndchrm train  -mlc  train-tif-v2/train_0.tif  train.fit**
```
Adding 'train-tif-v2/train_0-c-l.sig' for sig calc.
processing 'train-tif-v2/train_0-c-l.sig' (index 0).
wndchrm: Eigen/src/Core/DenseCoeffsBase.h:114: Eigen::DenseCoeffsBase<Derived, 0>::CoeffReturnType Eigen::DenseCoeffsBase<Derived, 0>::operator()(Eigen::DenseCoeffsBase<Derived, 0>::Index, Eigen::DenseCoeffsBase<Derived, 0>::Index) const [with Derived = Eigen::Map<Eigen::Matrix<HSVcolor, -1, -1, 1>, 1>; Eigen::DenseCoeffsBase<Derived, 0>::CoeffReturnType = const HSVcolor&; Eigen::DenseCoeffsBase<Derived, 0>::Index = long int]: Assertion `row >= 0 && row < rows() && col >= 0 && col < cols()' failed.
Aborted (core dumped)

```
In Windows sharing the same file system:
>**dir train_0*.***
. . .
```
2017-05-10  23:50                 0 train_0-c-l.sig
2017-05-10  23:51           126,246 train_0-l.sig
2017-05-10  23:51            40,788 train_0.sig
2017-04-26  18:11           524,592 train_0.tif
               4 File(s)        691,626 bytes

```              
The c-l.sig (color-long) file was never created.

**Comment by igg** [comment]
wndchrm will not compute color image files on 4-color tiffs - I'm pretty sure it will generate an error, but it depends on the exact structure.
I would recommend option 3.  There is now (in python) a way to specify features from more than a single image to use in a classification.  We've had a lot of success with this approach.
-Ilya

**Comment by EarlGlynn** [comment]
Thanks
