### ISSUE TITLE
inf and nan values for some features

### ISSUE THREAD

**Issue by beatrizserrano** [wnd-charm/wnd-charm#118]
Hi,

I'm analyzing images from the IDR using the wnd-charm Python API. When cropping and selecting channels, I've got `nan` and `inf` values for some images (see [this](https://github.com/idr-contrib/community/issues/9) thread for examples). We were wondering if this is due to the low difference in pixel intensities for some channels.

Thanks in advance!

**Comment by colettace** [comment]
Hi,
I'm curious what the histogram of the trouble pixel planes are. I looked at your image 171247 from [#9](https://github.com/idr-contrib/community/issues/9) and there's a lot of homogeneity in that region. In the WND-CHARM base use case, features that evaluate to nan and inf would simply be filtered out as uninformative, and I'm almost sure that's what's happening here. If it's easy for you, you can still try to confirm that it's not the cropping operation that's corrupting the pixel planes. The cropping code is [here](https://github.com/wnd-charm/wnd-charm/blob/master/src/cmatrix.cpp#L414). You can #define DEBUG 1 on line 30 and recompile and look at the output. Try  outputting the min/max/stdev of the object named matrix_OUT there to make sure the pixels aren't hosed. There are member methods on the ImageMatrix object to give you those quantities. HTH!
-Chris

**Comment by beatrizserrano** [comment]
Thanks, @colettace. My doubt was whether the features with nan/inf values indicate some kind of processing error or simply a lack of information. As you confirmed, the latter is the case, which makes sense to me. I don't think cropping is corrupting the plane since I've analyzed many other images using the same ROI and haven't found any trouble so far.

Beatriz.
