### ISSUE TITLE
Feature extraction

### ISSUE THREAD

**Issue by miki208** [wnd-charm/wnd-charm#119]
Is this the proper way of feature extraction?

`data = FeatureSpace.NewFromDirectory(input_dir, n_jobs=True)`
`pd.DataFrame(data.data_matrix, columns = data.feature_names).to_csv(output, index= False)`

Also, this code extracts only features, but not corresponding classes. How can I get corresponding classes?

**Comment by colettace** [comment]
Classes are represented by subdirectories which contain images in <code>input_dir</code>. The subdirectory names become the labels, and the labels are stored in <code>self._contiguous_ground_truth_labels</code>. HTH!
