### ISSUE TITLE
Python API 0.9 regular expressions don't compile in Python 2.6

### ISSUE THREAD

**Issue by colettace** [wnd-charm/wnd-charm#46]
As of right now, the latest release seems to be broken for Python 2.6. The following error message was obtained running python unittest discovery on Centos 6.6 machine running Python 2.6.6 (got a ton of these):

    Traceback (most recent call last):
      File "test_FeatureSpacePredictionExperiment.py", line 36, in <module>
        from wndcharm.ArtificialFeatureSpace import CreateArtificialFeatureSpace_Continuous
      File "/data/colettace/src/wnd-charm/build/lib.linux-x86_64-2.6/wndcharm/ArtificialFeatureSpace.py", line 72, in <module>
        from .FeatureSpace import FeatureSpace
      File "/data/colettace/src/wnd-charm/build/lib.linux-x86_64-2.6/wndcharm/FeatureSpace.py", line 50, in <module>
        class FeatureSpace( object ):
      File "/data/colettace/src/wnd-charm/build/lib.linux-x86_64-2.6/wndcharm/FeatureSpace.py", line 63, in FeatureSpace
        channel_col_finder = re.compile(r'(?P<path>.*?)?\{(?P<opts>.*?)?\}')
      File "/usr/lib64/python2.6/re.py", line 190, in compile
        return _compile(pattern, flags)
      File "/usr/lib64/python2.6/re.py", line 245, in _compile
        raise error, v # invalid expression
    sre_constants.error: nothing to repeat

The regular expression in question uses named matches for parsing. They are class attributes on the  FeatureSpace and FeatureVector objects, and if they don't compile it renders the whole package useless.

The named matching functionality gets used in FeatureSpace.NewFromFileOfFiles and FeatureVector.LoadSigFile. Maybe as a workaround do lazy compile of these re's when you call those functions so at least you can use other parts of the package. If we're going to continue to support 2.6 we'll need to rewrite those two functions using 2.6 friendly syntax.

**Comment by colettace** [comment]
@igg

**Comment by igg** [comment]
Isn't this a thing that can be imported from the __future__?

**Comment by igg** [comment]
Its probably OK to drop support for 2.6, but only if we provide a recipe for how to install 2.7 on something still commonly used like CentOS 6.  We can add recipes, etc. right to this issue.
We should also see about supporting python3, since running only on 2.7 is probably not the best.

**Comment by colettace** [comment]
To get the WND-CHARM Python API working on your CentOS6 machine, you should install Python 2.7 and the required third party packages. 

The easy way of getting it is to download an all-in-one Python distribution like [https://store.continuum.io/cshop/anaconda/](Anaconda), but it's a massive download and gives you way more 3rd party packages than you actually need.

If you want a leaner Python 2.7 install like I did, follow these generalized steps (more detailed instructions are at [http://toomuchdata.com/2014/02/16/how-to-install-python-on-centos/](this link)):

1. Download the latest Python 2.7 tarball from [https://www.python.org/downloads/](here).
2. Unzip.
3. IMPORTANT "ALTINSTALL"STEP: Make the binaries and install them somewhere. by using <code>make altinstall</code> this prefaces most  If you have administrative (sodo-er) privileges, you can just put the libraries in <code>/usr/local</code> (see commands below) otherwise you'll have to specify the foo/bar in the <code>./configure --prefix=/foo/bar</code> as detailed in the link above, and put that prefix in your <code>$PATH</code>.
    1. <code>./configure</code>
    2. <code>make</code>
    3. <code>sudo make altinstall</code>
5. Download and unzip the latest pip tarball, which at the time of this writing is [https://pypi.python.org/pypi/pip/7.1.0](7.1.0)
6. <code>sudo python2.7 setup.py install</code> NOTE the specification of the <code>python2.7</code> suffix. Otherwise, you'll end up accidentally using the Python 2.6 that comes with CentOS.
7. Previous steps puts the suffix "2.7" on ALMOST all the installed files in <code>/usr/local</code>. Go in there and <code>sudo mv</code> any file that didn't get a 2.7 suffix to have one. E.g., the pip installation will install pip as pip2 instead of pip2.7
8. <code>sudo pip2.7 install numpy scipy matplotlib ipython</code>
