### ISSUE TITLE
Need to run wndchrm classifier source code over MS Visual Studio at Windows 8 platform, and do modification in feature selection?

### ISSUE THREAD

**Issue by mhammadpk** [wnd-charm/wnd-charm#89]
Hi all,

I am working on an application which is using wndchrm.exe file placed at
http://vfacstaff.ltu.edu/lshamir/downloads/ImageClassifier/. 

Now, we need to modify the source code of wndchrm. For this purpose, I tried to create a new project for wndchrm, and include all the source files, written in C++ in the project, but it is giving me  errors mostly related to libraries, and environmental errors. I want to ask that "Is there any possibility, that I can successfully run the  source code in windows 8 by using MS visual studio?"

Secondly, as the wndchrm classifier code successfully filter out the informative features by using Fisher algorithm. I need to modify this step, by first exporting all the features calculated by wndchrm, and apply different algorithm in order to select informative features afterwards.

Can you please assist me how can I do it? Which file or functions should I need to study in order to this modification?

Please reply me, I will be thankful to you.

**Comment by colettace** [comment]
Hello from Baltimore, Maryland!
Sorry, but our particular fork of WND-CHARM doesn't currently support Windows and we have no plans to in the short term. There are a number of things you can try:

1. Not sure which version of wnd-charm you're using, but you may be able to modify the features used with the executable you have now. The -v option *should* allow you to read/write feature weights to/from a file. In addition the -f option allows you to set the cutoff for the minimum number of features used, e.g., using the option -f1.0 will direct wndcharm to use all the features calculated. You can use some combination of these two options to have finer control over the feature space, or use feature weights calculated by your different algorithm. For example, you can exclude any feature from consideration by the classifier by setting that feature weight to 0 in the feature weight file imported via the -v option.
2. With regard to your first issue of running on Windows, pretty much your only option is to set up a Virtual Machine. Install Oracle VirtualBox (free), then download a Linux distribution like Ubuntu, and have that be your WND-CHARM environment.
3. If you decide on option 2 above, then you can use the WND-CHARM Python API to write a Python script to set up your own image pipeline, swapping out Fisher feature weights for anything else you might want.

Hope that helps!
Chris

**Comment by mhammadpk** [comment]
Thanks Chris for your assistance.

I have following few concerns:

1. I have used "-l" command, in order to extract large features sets of pollen data set which is publicly available, by using following command in Windows environment:

 "wndchrm train -l pollen dataset.fit"

[dataset.zip](https://github.com/wnd-charm/wnd-charm/files/270585/dataset.zip)

But it is giving me 2885 features instead of 2695 features, as mentioned in the paper. Why it is giving me more? Please clarify:

2. Secondly, as you mentioned, if I choose step 2 in order to run the source code using virtual box, I need to write Python script.

Can I do changes in C++ source code, instead of writing Python script, in order to use different algorithm for selecting informative features and classification, as I don't have an idea about Python?

3. Finally, if it allows me to change the logic of wndchrm algorithm, using C++ in Linux environment, how can I get executable file for Windows environment in order to work with Visual Studio later on?

Please let me know about these concerns.
