### ISSUE TITLE
Regardin python API

### ISSUE THREAD

**Issue by jagadeesh09** [wnd-charm/wnd-charm#95]
when I am doing like below 
`from wndcharm.FeatureVector import FeatureVector`
I am geting the following error
 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/username/anaconda/lib/python2.7/site-packages/wndcharm-0.9.14-py2.7-linux-x86_64.egg/wndcharm/__init__.py", line 27, in <module>
    from wndcharm import *
  File "/home/username/anaconda/lib/python2.7/site-packages/wndcharm-0.9.14-py2.7-linux-x86_64.egg/wndcharm/wndcharm.py", line 28, in <module>
    _wndcharm = swig_import_helper()
  File "/home/username/anaconda/lib/python2.7/site-packages/wndcharm-0.9.14-py2.7-linux-x86_64.egg/wndcharm/wndcharm.py", line 20, in swig_import_helper
    import _wndcharm
ImportError: /home/username/anaconda/lib/python2.7/site-packages/wndcharm-0.9.14-py2.7-linux-x86_64.egg/_wndcharm.so: undefined symbol: _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEED1Ev

What is the reason for this? and how to resolve it

**Comment by colettace** [comment]
Hi,

So I can get an understanding of your configuration, can you run the following python code:
`from wndcharm import diagnostics; print diagnostics`

Also, can you run the following code in your bash shell:
`swig -version`

Thanks,
Chris

**Comment by jagadeesh09** [comment]
This is the output I got when I ran the above two commands
>>> from wndcharm import diagonistics
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jagadeesh/anaconda/lib/python2.7/site-packages/wndcharm-0.9.14-py2.7-linux-x86_64.egg/wndcharm/__init__.py", line 27, in <module>
    from wndcharm import *
  File "/home/jagadeesh/anaconda/lib/python2.7/site-packages/wndcharm-0.9.14-py2.7-linux-x86_64.egg/wndcharm/wndcharm.py", line 28, in <module>
    _wndcharm = swig_import_helper()
  File "/home/jagadeesh/anaconda/lib/python2.7/site-packages/wndcharm-0.9.14-py2.7-linux-x86_64.egg/wndcharm/wndcharm.py", line 20, in swig_import_helper
    import _wndcharm
ImportError: /home/jagadeesh/anaconda/lib/python2.7/site-packages/wndcharm-0.9.14-py2.7-linux-x86_64.egg/_wndcharm.so: undefined symbol: _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEED1Ev
>>> swig -version
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>

 swig -version

SWIG Version 3.0.8

Compiled with g++ [x86_64-pc-linux-gnu]

Configured options: +pcre

Please see http://www.swig.org for reporting bugs and further information

**Comment by colettace** [comment]
This is a compilation problem. What method did you use to install WND-CHARM? pip? Git clone then `python setup.py install`? Download the tarball and then `python setup.py install`? Perhaps some sort of Anaconda-specific command like `conda`?

All I can say is you have to reinstall everything as cleanly as possible. This will be specific to whatever you used to install WND-CHARM in the first place. So this means you would choose from solutions like `pip install --force https://github.com/wnd-charm/wnd-charm.git`, `sudo rm -rf /home/jagadeesh/anaconda/lib/python2.7/site-packages/wndcharm-0.9.14-py2.7-linux-x86_64.egg` ... We don't support installation via conda right now, so if that's what you did, maybe best to use the Anaconda-provided `pip` installer, or just `git clone https://github.com/wnd-charm/wnd-charm.git` and go in there and run `sudo python setup.py install` in bash.

**Comment by jagadeesh09** [comment]
I did git clone and then `python setup.py install` . 

But, why am i getting these type of warnings?

Type’ locally defined but not used [-Wunused-local-typedefs]
     typedef typename ComplexSchur<MatrixType>::ComplexMatrixType ComplexMatrixT
                                                                  ^
src/Tasks.cpp: In destructor ‘ComputationTaskInstances::~ComputationTaskInstances()’:
src/Tasks.cpp:86:25: warning: deleting object of abstract class type ‘ComputationTask’ which has non-virtual destructor will cause undefined behaviour [-Wdelete-non-virtual-dtor]
   delete (instances[idx]);
                         ^
src/Tasks.cpp: In member function ‘virtual void FeatureComputationPlanExecutor::execute_node(const ComputationTaskNode*)’:
src/Tasks.cpp:252:69: warning: ‘t1’ may be used uninitialized in this function [-Wmaybe-uninitialized]
         std::cout << "TIME\t" << exec_node->name << "\t" << (t2 - t1) << std::e
                                                                     ^
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I./ -Isrc/ -I/usr/local/include -I/usr/include/python2.7 -c src/FeatureNames.cpp -o build/temp.linux-x86_64-2.7/src/FeatureNames.o
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++

And finally there is a scipy package. But it's unable to recognize!

**Comment by colettace** [comment]
Those are warnings, errors. They're not the cause of your problem.

Not sure what you mean "unable to recognize" with respect to the scipy package. WND-CHARM's interaction with scipy is subsequent to importing the package, which is where the error is occurring. 

I need to be able to reproduce your error in order to fix your problem. I've never seen this error before. Can you give me as much information as possible about the OS you're using, the compiler you're using. 

Also, can you run this command and put the output in Pastebin or something similar so I can see:
`nm /home/username/anaconda/lib/python2.7/site-packages/wndcharm-0.9.14-py2.7-linux-x86_64.egg/_wndcharm.so | c++filt`

**Comment by colettace** [comment]
Looking back over your error messages it seems you've reported two different paths to the faulty .so file. The path to the .so file in the command I asked you to run in my last comment is `/home/username/.../_wndcharm.so`, but then I also see you've reported a problem with a fle in a different directory, namely `/home/jagadeesh/.../_wndcharm.so`. The general command I'd like you to run is `nm </path/to/_wndcharm.so> | c++filt`. See if you can get that output so we can help you get up and running.

**Comment by jagadeesh09** [comment]
Thanks a lot Chris! It's working. I
s there any documentation for using python API ?

**Comment by colettace** [comment]
Good! See the examples directory, and also take a look at the the unittests that are in the tests/pywndcharm_tests directory.
